#!/usr/bin/env python3
"""Compute permutation-candidate stats vs fully-generic sign diagrams.

For each entry in ``tests/all_knots.yaml`` (or a user-supplied YAML file), this
script computes:

- how many *closed* permutation candidates are generated by
  ``fkcompute.inversion.permutations.iter_perms_rot_closed``
- how many fully-generic sign diagrams exist for the braid closure, i.e.
  ``2 ** n_s_total`` where ``n_s_total`` is the number of independent sign
  variables used by ``fkcompute.domain.braid.BraidTopology``.

Output defaults to CSV on stdout.
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
import time
from pathlib import Path
from typing import Any, Dict, Iterator, Tuple


def _import_yaml() -> Any:
    try:
        import yaml  # type: ignore

        return yaml
    except ModuleNotFoundError as e:
        raise SystemExit(
            "PyYAML is required to run this script. Install with: pip install .[yaml]"
        ) from e


def _ensure_src_on_path() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    src = repo_root / "src"
    if str(src) not in sys.path:
        sys.path.insert(0, str(src))


def _iter_yaml_braids(yaml_path: Path) -> Iterator[Tuple[str, list[int]]]:
    yaml = _import_yaml()
    data = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"Expected a mapping at top level in {yaml_path}")
    for name, spec in data.items():
        if not isinstance(spec, dict) or "braid" not in spec:
            continue
        braid = spec["braid"]
        if not isinstance(braid, list) or not all(isinstance(x, int) for x in braid):
            raise ValueError(f"Invalid braid for {name!r} in {yaml_path}")
        yield str(name), list(braid)


def _count_closed_perms(braid: list[int]) -> int:
    from fkcompute.inversion.permutations import iter_perms_rot_closed

    return sum(1 for _ in iter_perms_rot_closed(braid))


def _fully_generic_count(braid: list[int]) -> Tuple[int, int, int]:
    """Return (n_components, n_s_total, fully_generic_count)."""
    from fkcompute.domain.braid.states import BraidStates

    bs = BraidStates(braid)
    n_components = int(bs.n_components)
    n_s_total = int(bs.n_s_total)
    return n_components, n_s_total, 1 << n_s_total


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Count closed permutation candidates vs fully-generic sign diagrams "
            "for every braid in a YAML file."
        )
    )
    parser.add_argument(
        "--yaml",
        default="tests/all_knots.yaml",
        help="Path to YAML file (default: tests/all_knots.yaml)",
    )
    parser.add_argument(
        "--max-knots",
        type=int,
        default=None,
        help="Process at most this many entries (debugging)",
    )
    parser.add_argument(
        "--progress-every",
        type=int,
        default=50,
        help="Print a progress line to stderr every N knots (default: 50)",
    )

    args = parser.parse_args(argv)

    _ensure_src_on_path()

    yaml_path = Path(args.yaml)
    if not yaml_path.exists():
        print(f"YAML file not found: {yaml_path}", file=sys.stderr)
        return 2

    writer = csv.DictWriter(
        sys.stdout,
        fieldnames=[
            "name",
            "n_crossings",
            "n_components",
            "n_s_total",
            "perm_candidates_closed",
            "fully_generic_sign_diagrams",
            "ratio_candidates_over_full",
            "log2_ratio_candidates_over_full",
            "seconds",
            "error",
        ],
    )
    writer.writeheader()

    processed = 0
    errors = 0
    t0 = time.time()

    for idx, (name, braid) in enumerate(_iter_yaml_braids(yaml_path), start=1):
        if args.max_knots is not None and idx > args.max_knots:
            break
        processed = idx

        row: Dict[str, Any] = {
            "name": name,
            "n_crossings": len(braid),
            "n_components": "",
            "n_s_total": "",
            "perm_candidates_closed": "",
            "fully_generic_sign_diagrams": "",
            "ratio_candidates_over_full": "",
            "log2_ratio_candidates_over_full": "",
            "seconds": "",
            "error": "",
        }

        knot_t0 = time.time()
        try:
            n_components, n_s_total, full_count = _fully_generic_count(braid)
            perm_count = _count_closed_perms(braid)
            dt = time.time() - knot_t0

            row["n_components"] = n_components
            row["n_s_total"] = n_s_total
            row["perm_candidates_closed"] = perm_count
            row["fully_generic_sign_diagrams"] = full_count
            if perm_count > 0:
                # Stable ratio computations without materializing huge floats.
                row["ratio_candidates_over_full"] = math.ldexp(float(perm_count), -n_s_total)
                row["log2_ratio_candidates_over_full"] = math.log2(perm_count) - n_s_total
            else:
                row["ratio_candidates_over_full"] = 0.0
                row["log2_ratio_candidates_over_full"] = "-inf"
            row["seconds"] = dt
        except Exception as e:  # noqa: BLE001 - keep going across a large corpus
            errors += 1
            row["error"] = f"{type(e).__name__}: {e}"
            row["seconds"] = time.time() - knot_t0

        writer.writerow(row)

        if args.progress_every and (processed % int(args.progress_every) == 0):
            elapsed = time.time() - t0
            print(
                f"processed={processed} errors={errors} elapsed={elapsed:.1f}s",
                file=sys.stderr,
            )

    elapsed = time.time() - t0
    print(
        f"done processed={processed} errors={errors} elapsed={elapsed:.1f}s",
        file=sys.stderr,
    )
    return 0 if errors == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
